version: '3.4'

services:
  healthcare.webui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081 
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  healthcare.api:
    environment:
      - ConnectionStrings__DefaultConnection=Server=healthcaredb;Database=Healthcare;User Id=sa;TrustServerCertificate= True; Integrated Security= SSPI
    ports:
      - "8082:80"
    
  healthcare.db:
    ports:
     - "1433:1433"